- src/Components/Health/Checker/MysqlChecker.php
- src/Components/Health/Checker/PhpChecker.php
- src/Resources/app/administration/src/overrides/sw-version/index.js
- src/Resources/config/services.xml
Add status updating every 10 seconds,
Add check for active Opcache in PhpChecker,
Added new MysqlChecker
> some additions

- src/Controller/CacheController.php
> Sort result of CacheStatistics

- src/Components/CacheAdapter.php
- on certain installations "$this->adapter->clear();" won't have any effect on redis (swdc f.e.).
- on certain installations "on certain installations "$this->adapter->clear();" won't have any effect on redis (swdc f.e.)." will crash  (timmehosting f.e.).
Fixes #25
> fix: redis sizes and redis-clear

- src/Components/Messenger/TaskLoggingMiddleware.php
- remove useless `else if`
- add `IterateEntityIndexerMessage` to argumentextraction
- set duration always at the beginning of the arguments
- log exception as error instead of info
> fix: refactor TaskLoggingMiddleware

- src/Components/Elasticsearch/EsProductDefinition.php
See -> https://github.com/FriendsOfShopware/FroshTools/issues/85
> Add extendEntities method

- composer.json
I think you have mixed up one little thing. Fixed it.
> Fix manufacturerLink and supportLink in composer.json

- src/Components/Health/Checker/PerformanceChecker/PhpSettingsChecker.php
> fix: php ini with value 0 misinterpreted, added helper function

- src/Components/Health/Checker/HealthChecker/QueueChecker.php
There seems to be another false positive: The `QueueChecker` uses `messenger_messages.created_at` for its logic, but this doesn't take into account messages with Symfony's `DelayStamp`.
An easy way to trigger this is by running `bin/console theme:compile`, which would always cause `FroshTools` to report a warning for me due to a purposely delayed message waiting in the queue.
From what I can tell, Symfony Messenger _itself_ uses the `available_at` column: https://github.com/symfony/doctrine-messenger/blob/85d3c2c2e1d0c7c6828c279534b2956a93a0ad6d/Transport/Connection.php#L172
Furthermore, previously there was an `(int)` cast on the SQL query result that silently converted the string returned by Doctrine (`"2023-05-31 09:58:08"`) to the integer `2023`.
> fix: correct detection of delayed message queues

- src/Controller/ShopwareFilesController.php
- src/DependencyInjection/Configuration.php
- src/DependencyInjection/FroshToolsExtension.php
- src/FroshTools.php
- src/Resources/app/administration/package-lock.json
- src/Resources/app/administration/package.json
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-files/index.js
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-files/template.twig
- src/Resources/app/administration/src/module/frosh-tools/index.js
- src/Resources/app/administration/src/module/frosh-tools/page/index/template.twig
- src/Resources/app/administration/src/module/frosh-tools/snippet/de-DE.json
- src/Resources/app/administration/src/module/frosh-tools/snippet/en-GB.json
- src/Resources/config/services.xml
This PR brings back the ShopwareFilesChecker.
Additionally, it adds support for platform-installations.
Closes #201
> feat: add ShopwareFilesChecker

- src/Resources/app/administration/src/api/frosh-tools.js
> fix: check login status before requesting healthStatus

- CHANGELOG_en-GB.md
- composer.json
- src/Controller/ScheduledTaskController.php
- src/Resources/config/config.xml
- Fixes problems with manual execution of Scheduled Tasks
-> calls the __invoke() method of the abstract ScheduledTaskHandler, In this function, the status of the tak is set correctly and the rescheduleTask function is executed.
> Fixed Scheduled Tasks

- src/Components/Health/Checker/HealthChecker/PhpChecker.php
https://php.watch/versions/8.2/ini_parse_quantity
I don't think it is worth creating an entire polyfill 🙈
> feat: use ini_parse_quantity if available

- .gitpod.Dockerfile
- src/Command/MonitorCommand.php
- src/Components/CacheAdapter.php
- src/Components/Health/Checker/PerformanceChecker/PhpSettingsChecker.php
- src/Components/Health/Checker/PerformanceChecker/RedisTagAwareChecker.php
- src/Components/SystemConfig/ConfigSystemConfigLoader.php
> feat: recommend zend.assertions instead of assert.active and RedisTagAware

- composer.json
- src/Components/Health/Checker/PerformanceChecker/RedisTagAwareChecker.php
- src/Controller/LogController.php
- src/Controller/StateMachineController.php
> feat: recommend RedisTagAware from Shopware 6.5.8.0

- composer.json
- src/Components/Health/Checker/HealthChecker/SwagSecurityChecker.php
Will move it also to main, if it's okay.
Closes #244
> feat: add warning for outdated shopware

- src/Components/Health/Checker/PerformanceChecker/MysqlSettingsChecker.php
Regarding the docs, there should be NO `ONLY_FULL_GROUP_BY`. But the current check want to have it set.
> fix: correct check for set SQL_Mode

- src/Controller/LogController.php
> feat: allow handling of log files within subfolders

- src/Resources/app/administration/src/module/frosh-tools/index.js
> Fix broken back button in module

- src/Components/Health/Checker/PerformanceChecker/PhpSettingsChecker.php
> fix: correctly interpret ini values in PhpSettingsChecker

- README.md
- src/Components/Health/Checker/HealthChecker/SystemTimeChecker.php
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-cache/index.js
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-cache/template.twig
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-elasticsearch/index.js
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-elasticsearch/template.twig
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-files/template.twig
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-index/template.twig
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-logs/template.twig
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-queue/index.js
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-queue/template.twig
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-scheduled/index.js
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-scheduled/template.twig
- src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-state-machines/template.html.twig
- src/Resources/app/administration/src/module/frosh-tools/page/index/template.twig
- src/Resources/app/administration/src/module/frosh-tools/snippet/de-DE.json
- src/Resources/app/administration/src/module/frosh-tools/snippet/en-GB.json
Currently, some snippets are missing, and others are not entirely consistent.
This PR aims to unify the snippets and add all missing snippets to the translation JSON files.
> Unify snippets

- .shopware-extension.yml
- composer.json
- src/Resources/store/de.md
- src/Resources/store/en.md
- **chore: update store information**
- **chore: release 3.0.0**
> chore: update store infomation and release 3.0.0

- composer.json
- src/Components/Health/Checker/HealthChecker/PhpFpmChecker.php
> feat: degrade check for fpm checks to an info instead warning
