CHANGELOG_de-DE.md
CHANGELOG_en-GB.md
composer.json
src/Components/Health/Checker/ProductionChecker.php
src/Resources/app/administration/src/module/frosh-tools/snippet/de-DE.json
src/Resources/app/administration/src/module/frosh-tools/snippet/en-GB.json

The system status entry disappears, when the shop is in production mode. Added missing status message for the production check.

Added positive status message for the production mode check

---

.github/workflows/store.yml
CHANGELOG_de-DE.md
CHANGELOG_en-GB.md
composer.json

- there was no 0.1.1 yet
- we should prevent store data to be updated with content not yet valid for released versions

chore: updated changelog

---

src/Components/Health/Checker/TaskChecker.php

If a task is set to inactive, the status always reports as unhealthy, because inactive tasks may not running for a long period. By excluding inactive tasks, the state can be reported correctly.

Exclude inactive tasks from health check

---

src/Controller/ScheduledTaskController.php

The method `AbstractMessageHandler::getHandledMessages()` has `iterable` as its return type, but the code in
`ScheduledTaskController` assumed that its result can be passed as the second argument to `in_array()`. This causes errors when using the "start manually" button in the scheduled tasks manager UI.
Change this to convert the result into an array before passsing it into `in_array()`.

fix: handle `iterable` response in scheduled task controller

---

src/Controller/ScheduledTaskController.php

https://github.com/shopware/platform/blob/37dcd398e8429c0f7d9cdfa79d9df72b44955390/src/Core/Framework/MessageQueue/ScheduledTask/ScheduledTaskHandler.php#L85
Running the task manually will add the intervall onto existing nextExecutionTime, which can be result in task unexpected running in the distant future.

fix: set nextExecutionTime to prevent stacking of calculating nextExecutionTime

---

src/Command/MonitorCommand.php
src/Components/Elasticsearch/EsProductDefinition.php
src/Components/Messenger/TaskLoggingMiddleware.php
src/Resources/config/config.xml
src/Resources/config/services.xml

As talked about with @shyim in Slack here is a simple integration with email instead of webhooks.
The integration with the notifier component from symfony is nice as well, but uses the message queue to send messages. There is always the possibility of adding an own webhook interface, but probably just overkill atm (as well as adding an own mailtemplate/migration etc. to the mail integration).
Feel free to mention the other dev that you referred to.
**Usage**
3 configs are added
- Mail
- Grace time for queue (those are curerntly fixed in the code of the healthchecker)
- Grace time for task (those are curerntly fixed in the code of the healthchecker)
**First argument must be a Saleschannel ID**
`bin/console frosh:monitor 4606300361c34ae3b69d813bb292f823`
**Email can be overwritten in …

Add mailing command

---

src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-queue/index.js
src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-queue/style.scss
src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-queue/template.twig
src/Resources/app/administration/src/module/frosh-tools/snippet/de-DE.json
src/Resources/app/administration/src/module/frosh-tools/snippet/en-GB.json

- Make refresh fancy again
- Moved reset action button to grid header like in scheduled tasks
- Added snippets
- Removed empty grid actions column
Before:
After:
<a href="https://gitpod.io/#https://github.com/FriendsOfShopware/FroshTools/pull/136"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Visual Queue-Tab update

---

src/Controller/CacheController.php
src/Controller/ElasticsearchController.php
src/Controller/FeatureFlagController.php
src/Controller/HealthController.php
src/Controller/LogController.php
src/Controller/QueueController.php
src/Controller/ScheduledTaskController.php
src/Controller/ShopwareFilesController.php
src/Controller/StateMachineController.php
src/Resources/app/administration/src/module/frosh-tools/acl/index.js
src/Resources/app/administration/src/module/frosh-tools/index.js
src/Resources/app/administration/src/module/frosh-tools/page/index/frosh-tools.scss
src/Resources/app/administration/src/module/frosh-tools/snippet/de-DE.json
src/Resources/app/administration/src/module/frosh-tools/snippet/en-GB.json
src/Resources/app/administration/src/overrides/sw-version/index.js
src/Resources/app/administration/src/overrides/sw-version/template.twig

I have added an ACL where the users need to have permissions to acces the FroshTool monitoring. This way, not every user in the administration can access the monitoring.
When the user does not have these permissions, they will not have acces to the individual pages from the FroshTool monitoring and they will not have the custom health badge.
I also fixed a small bug where the the back button would not send you to the index page. This was due to the parentPath being 'frosh.tools.index' instead of 'frosh.tools.index.index'
<a href="https://gitpod.io/#https://github.com/FriendsOfShopware/FroshTools/pull/141"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>

Add ACL to FroshTool

---

src/Components/Health/Checker/PerformanceChecker/EsChecker.php

Hey guys,
while using your plugin, I noticed that the link to the Elasticsearch-Setup is not up-to-date anymore. 
I fixed this tiny bug in my pull request. Hope it helps :)

fix(EsChecker): updated link

---

src/Components/Health/Checker/HealthChecker/TaskChecker.php

see https://www.php.net/manual/en/class.dateinterval.php#dateinterval.props

fix: task checker interval compare minutes instead of months

---

src/Command/EnvDelCommand.php

Isn't it nicer to have `frosh:env:del` instead of `frosh:env:list`?

Turn command into lowercase

---

CHANGELOG_en-GB.md
README.md
src/Command/DevRobotsTxtCommand.php
src/Command/MonitorCommand.php
src/Resources/app/administration/src/module/frosh-tools/snippet/de-DE.json
src/Resources/app/administration/src/module/frosh-tools/snippet/en-GB.json
src/Resources/store/de.md
src/Resources/store/en.md

- Fix spelling in a number of files & swap snippet "frosh-tools.tabs.index.performance" between "de_DE" and "en_GB"
- Add missing command "frosh:monitor" to README.md
- Move description for command "frosh:dev:robots-txt" to AsCommand attribute

Fix spelling & formatting, add command to README.md

---

src/Resources/app/administration/src/module/frosh-tools/index.js

The name will be displayed in the twig key parameter, label seems to be for translated names.

fix name/label in admin index.js module registration

---

src/Components/StateMachines/Mermaid.php
src/Controller/StateMachineController.php
src/Resources/views/administration/mermaid/state-machine.html.twig

Adds a API endpoint for getting mermaid flowcharts
GET {{url}}/api/_action/frosh-tools/state-machines/load-mermaid?stateMachine=order_transaction.state
GET {{url}}/api/_action/frosh-tools/state-machines/load-mermaid?stateMachine=order_delivery.state
GET {{url}}/api/_action/frosh-tools/state-machines/load-mermaid?stateMachine=order.state
Example response:
`{
"data": "flowchart TD\nSTART_STATE[Start state] --> 0189e474ee557113994b4f678ba7574a\n\n0189e474ee557113994b4f678ba7574a(Open)\n0189e474ee557113994b4f678c711eb7(Cancelled)\n0189e474ee557113994b4f678c711eb7 --> FINAL_STATE[Final state]\n0189e474ee557113994b4f678d696964(Shipped)\n0189e474ee557113994b4f678db3c16c(Shipped partially)\n0189e474ee557113994b4f678e1eb368(Returned)\n0189e474ee557113994b4f678e1eb368 --> FINAL_STATE[Final …

Add route, template and export

---

src/Resources/app/administration/src/module/frosh-tools/index.js

Currently every user see this icon and the whole settings/extensions/tools navigation path.
Now its gone

Add privileges to settings item

---

src/Controller/StateMachineController.php
src/Resources/app/administration/src/api/frosh-tools.js
src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-state-machines/index.js
src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-state-machines/style.scss
src/Resources/app/administration/src/module/frosh-tools/component/frosh-tools-tab-state-machines/template.html.twig

- Replaced `sw-select` with `sw-entity-single-select` to load all available StateMachines
- Changed Route to load stateMachine Plantuml image by `id` instead of `technicalName`
- Adjust view
New view:

Refactor the StateMachineViewer component

---

src/Command/MonitorCommand.php
src/Components/Health/Checker/HealthChecker/QueueChecker.php

Currently the `QueueChecker` shows a warning when a delayed message is dispatched (for example after `bin/console theme:compile`). This gets fixed by ignoring messages which should be handled in the future.
Also the `MonitoringCommand` isn't working correctly. It is using the `created_at` column instead of `available_at`. Furthermore there is an error while casting the date-string to an integer. `"2024-01-18 14:08:32"` becomes `2024` which then gets used as a timestamp which is obviously wrong. This gets fixed by using the `strtotime()` function.

Fix message queue monitoring

---

src/Components/Health/Checker/HealthChecker/MysqlChecker.php

we might have missed updating the requirements with 6.6. See: https://developer.shopware.com/release-notes/6.6/6.6.0.0.html#maria-db-10-11-minimum-requirement

fix: update min maria db to 10.11

---

src/Components/Health/Checker/HealthChecker/SwagSecurityChecker.php
src/Controller/ShopwareFilesController.php

Replaced usage of file_get_contents with Symfony’s HttpClientInterface in SwagSecurityChecker and ShopwareFilesController to handle HTTP requests.
This makes it possible to use FroshTools when allow_url_fopen is 0 in the PHP settings.

Use Symfony HttpClient

---

src/Controller/HealthController.php

It is not really an issue but it generates a lot of deprecation warnings, that should be cared about. Depending on the range of Shopware versions, that this is designed for we need switch around the use so we dynamically switch the name.

Replace deprecated TaggedIterator with new AutowireIterator

---

src/Components/Health/Checker/HealthChecker/TaskChecker.php

The message does not make sense, while 1 is lower than 10.

fix: correct reported overdue  for scheduled task

---

README.md

Removed in https://github.com/FriendsOfShopware/FroshTools/commit/dd077ecbcd705f871883bdb99e39464c389f0632 but still in the readme

chore: remove non-existing feature task logging

---

src/Components/Health/Checker/PerformanceChecker/MysqlSettingsChecker.php

This pull request introduces enhancements to the `MysqlSettingsChecker` class to improve the performance checks related to MySQL settings. The key changes include the addition of a new constant for MySQL time zones, the implementation of a new method to check the MySQL time zone, and the integration of this new check into the collection process.
Enhancements to MySQL settings checks:
* [`src/Components/Health/Checker/PerformanceChecker/MysqlSettingsChecker.php`](diffhunk://#diff-815f58af033c3e62ec4e00b41280346d3d1ddadcb53089efde1c1d7ab4eadf59R21-R25): Added a new constant `MYSQL_TIME_ZONES` to store acceptable MySQL time zones.
* [`src/Components/Health/Checker/PerformanceChecker/MysqlSettingsChecker.php`](diffhunk://#diff-815f58af033c3e62ec4e00b41280346d3d1ddadcb53089efde1c1d7ab4eadf59R34 …

MySQL settings checker: Add time_zone check

---

src/Components/Health/Checker/PerformanceChecker/MysqlSettingsChecker.php

MySQL's time zone check is currently wrong. It needs to be inverted.
Currently, a warning is issued if the database time zone is `UTC` or `+00:00` However, if the time zone does not match these values, a warning should be issued.
- See #321

Fix mysql timezone check
